### ISSUE TITLE
Testing accuracy not matching with value provided in paper.

### ISSUE THREAD

**Issue by suvra97** [carolchenyx/MGFN#13]
I am training using the exact code given in this repo on the features provided in the onedrive. However, I am unable to get the accuracy stated in the paper. I am getting somewhere around 85%. Is there something I am overlooking? Any help would be appreciated.

**Comment by carolchenyx** [comment]
Hi,  The checkpoint is selected based on the highest AUC same as the RTFM method and following the previous anomaly detection papers. You should get around 85.XX - 86.XX based on different random seeds.

**Comment by Iman-Mostafa** [comment]
> Hi, The checkpoint is selected based on the highest AUC same as the RTFM method and following the previous anomaly detection papers. You should get around 85.XX - 86.XX based on different random seeds.

can i know the accuracy you reached after 100 epochs please?
