### ISSUE TITLE
Feature Extraction Code

### ISSUE THREAD

**Issue by joefioresi718** [carolchenyx/MGFN#6]
Hello, could you release feature extraction code for the 10-crop features? I would like to experiment using different fine-tuned models. Thanks!

**Comment by a-balah** [comment]
I have similar question to this. Can you please provide the configuration for VideoSwin feature extractor and it's configuration for XD-violence?

**Comment by carolchenyx** [comment]
Dear all, for feature extraction, you can refer below repos:
https://github.com/Tushar-N/pytorch-resnet3d and https://github.com/haofanwang/video-swin-transformer-pytorch 
Thanks.

**Comment by yb-cs** [comment]
is it possible to upload the video-swine features please? Since one of the zip files provided by xd-violence authors is corrupted
