### ISSUE TITLE
[Inquiry] The Test set ground truth used in this repository 

### ISSUE THREAD

**Issue by AnasEmad11** [carolchenyx/MGFN#8]
Hello, 

Could you clarify why the ground truth labels in your (gt-ucf-renew.npy) provided in the Onedrive Link were changed for multiple abnormal videos (roadaccidents, shooting, shoplifting, stealing, vandalism)?

Many thanks for considering my request.

**Comment by carolchenyx** [comment]
Hi. Sorry, could you elaborate more？ I

**Comment by Songinpyo** [comment]
Following the ucf-i3d-test.list, the gt-ucf-renew.npy doesn't fit with GT annotations.

**Comment by quyiii** [comment]
I found the same problem, the ground truth labels of abnormal videos(roadaccidents, shooting, shoplifting, stealing, vandalism) are all 0 which is same as normal videos!

**Comment by carolchenyx** [comment]
Hi, could you show the visualizations? Please draw the visualization frame by frame, thx.

**Comment by quyiii** [comment]
> Hi, could you show the visualizations? Please draw the visualization frame by frame, thx.

such as Vandalism036_x264.mp4, I found it starts at 1112688 in gt_ucf and it's length is 1456 according to the make_gt_ucf.py of RTFM. Then I found the ground truth of Vandalism036 are all 0 which is different from the annotation: Vandalism036_x264.mp4  Vandalism  540  780  990  1080 .
<img width="761" alt="截屏2023-04-11 15 42 43" src="https://user-images.githubusercontent.com/98630400/231091502-646593c6-fb43-41eb-b1d0-8351be3244be.png">
